name: Build JDA Forge
on:
  push:
    branches: [ "master" ]
    paths:
      - build.gradle

permissions:
  contents: write

jobs:
  build:
    if: |
      github.actor != 'dependabot[bot]' &&
      github.actor != 'github-actions[bot]' &&
      !startsWith(github.actor, 'dependabot') &&
      !endsWith(github.event.head_commit.author.name, '[bot]') &&
      !contains(github.event.head_commit.message, '@skip')
    uses: RealMangorage/SharedActions/.github/workflows/gradle.yml@main
    with:
      java: 17
      gradle_tasks: :publish :publishCurseforge
      artifact_name: "JDA-Forge"
      artifact_group: "org.mangorage"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      PROMOTE_ARTIFACT_WEBHOOK: ${{ secrets.PROMOTE_ARTIFACT_WEBHOOK }}
      PROMOTE_ARTIFACT_USERNAME: ${{ secrets.PROMOTE_ARTIFACT_USERNAME }}
      PROMOTE_ARTIFACT_PASSWORD: ${{ secrets.PROMOTE_ARTIFACT_PASSWORD }}
      MAVEN_USER: ${{ secrets.USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.PASSWORD }}
